server.port=8080

spring.datasource.url=jdbc:mysql://localhost:3306/fundoo_notes?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=123456
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.secret.key=FundooSecretKeyForLearningProject
jwt.expiration.ms=86400000

logging.level.root=INFO
logging.level.com.fundoonotes=DEBUG

spring.data.redis.host=localhost
spring.data.redis.port=6379

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

# Disable Spring Batch auto job run on startup
spring.batch.job.enabled=false
